# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.srcs/sources_1/ip/l1_o_data_128x4096/l1_o_data_128x4096.xci
# IP: The module: 'l1_o_data_128x4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/l1_o_data_128x4096/l1_o_data_128x4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'l1_o_data_128x4096'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.srcs/sources_1/ip/l1_o_data_128x4096/l1_o_data_128x4096.xci
# IP: The module: 'l1_o_data_128x4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/l1_o_data_128x4096/l1_o_data_128x4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'l1_o_data_128x4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
