// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module AESL_axi_slave_axilite (
    clk,
    reset,
    TRAN_s_axi_axilite_AWADDR,
    TRAN_s_axi_axilite_AWVALID,
    TRAN_s_axi_axilite_AWREADY,
    TRAN_s_axi_axilite_WVALID,
    TRAN_s_axi_axilite_WREADY,
    TRAN_s_axi_axilite_WDATA,
    TRAN_s_axi_axilite_WSTRB,
    TRAN_s_axi_axilite_ARADDR,
    TRAN_s_axi_axilite_ARVALID,
    TRAN_s_axi_axilite_ARREADY,
    TRAN_s_axi_axilite_RVALID,
    TRAN_s_axi_axilite_RREADY,
    TRAN_s_axi_axilite_RDATA,
    TRAN_s_axi_axilite_RRESP,
    TRAN_s_axi_axilite_BVALID,
    TRAN_s_axi_axilite_BREADY,
    TRAN_s_axi_axilite_BRESP,
    TRAN_read_address,
    TRAN_write_address,
	TRAN_frame_size,		// NXT ++
	TRAN_width_height,		// NXT ++
    TRAN_axilite_write_data_finish,
    TRAN_axilite_start_in,
    TRAN_axilite_idle_out,
    TRAN_axilite_ready_out,
    TRAN_axilite_ready_in,
    TRAN_axilite_done_out,
    TRAN_axilite_write_start_in   ,
    TRAN_axilite_write_start_finish,
    TRAN_axilite_interrupt,
    TRAN_axilite_transaction_done_in
    );

//------------------------Parameter----------------------
`define TV_IN_read_address "../tv/cdatafile/c.ConvNormReluPoolWrapper.autotvin_read_address.dat"
`define TV_IN_write_address "../tv/cdatafile/c.ConvNormReluPoolWrapper.autotvin_write_address.dat"
parameter ADDR_WIDTH = 5;
parameter DATA_WIDTH = 32;
parameter read_address_DEPTH = 1;
reg [31 : 0] read_address_OPERATE_DEPTH = 1;
parameter read_address_c_bitwidth = 32;
parameter write_address_DEPTH = 1;
reg [31 : 0] write_address_OPERATE_DEPTH = 1;
parameter write_address_c_bitwidth = 32;
parameter START_ADDR = 0;
parameter ConvNormReluPoolWrapper_continue_addr = 0;
parameter ConvNormReluPoolWrapper_auto_start_addr = 0;
parameter read_address_data_in_addr 	= 16;	//	5'h10
parameter write_address_data_in_addr 	= 24;	//	5'h18
parameter width_height_data_in_addr  	= 20;	//	5'h14	// NXT ++
parameter frame_size_data_in_addr  		= 28;	//	5'h1c	// NXT ++
parameter STATUS_ADDR = 0;

output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_axilite_AWADDR;
output  TRAN_s_axi_axilite_AWVALID;
input  TRAN_s_axi_axilite_AWREADY;
output  TRAN_s_axi_axilite_WVALID;
input  TRAN_s_axi_axilite_WREADY;
output [DATA_WIDTH - 1 : 0] TRAN_s_axi_axilite_WDATA;
output [DATA_WIDTH/8 - 1 : 0] TRAN_s_axi_axilite_WSTRB;
output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_axilite_ARADDR;
output  TRAN_s_axi_axilite_ARVALID;
input  TRAN_s_axi_axilite_ARREADY;
input  TRAN_s_axi_axilite_RVALID;
output  TRAN_s_axi_axilite_RREADY;
input [DATA_WIDTH - 1 : 0] TRAN_s_axi_axilite_RDATA;
input [2 - 1 : 0] TRAN_s_axi_axilite_RRESP;
input  TRAN_s_axi_axilite_BVALID;
output  TRAN_s_axi_axilite_BREADY;
input [2 - 1 : 0] TRAN_s_axi_axilite_BRESP;
input    [32 - 1 : 0] TRAN_read_address;
input    [32 - 1 : 0] TRAN_write_address;
input    [32 - 1 : 0] TRAN_frame_size;	//NXT ++
input    [32 - 1 : 0] TRAN_width_height;	//NXT ++
output TRAN_axilite_write_data_finish;
input     clk;
input     reset;
input     TRAN_axilite_start_in;
output    TRAN_axilite_done_out;
output    TRAN_axilite_ready_out;
input     TRAN_axilite_ready_in;
output    TRAN_axilite_idle_out;
input  TRAN_axilite_write_start_in   ;
output TRAN_axilite_write_start_finish;
input     TRAN_axilite_interrupt;
input     TRAN_axilite_transaction_done_in;

reg [ADDR_WIDTH - 1 : 0] AWADDR_reg = 0;
reg  AWVALID_reg = 0;
reg  WVALID_reg = 0;
reg [DATA_WIDTH - 1 : 0] WDATA_reg = 0;
reg [DATA_WIDTH/8 - 1 : 0] WSTRB_reg = 0;
reg [ADDR_WIDTH - 1 : 0] ARADDR_reg = 0;
reg  ARVALID_reg = 0;
reg  RREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] RDATA_reg = 0;
reg  BREADY_reg = 0;
reg [read_address_c_bitwidth - 1 : 0] 	reg_read_address;
reg 									read_address_write_data_finish;

reg [write_address_c_bitwidth - 1 : 0] 	reg_write_address;
reg 									write_address_write_data_finish;

reg [32 - 1 : 0] reg_frame_size;				// NXT ++
reg 			 frame_size_write_data_finish; 	// NXT ++

reg [32 - 1 : 0] reg_width_height;				// NXT ++
reg 			 width_height_write_data_finish; // NXT ++

reg AESL_ready_out_index_reg = 0;
reg AESL_write_start_finish = 0;
reg AESL_ready_reg;
reg ready_initial;
reg AESL_done_index_reg = 0;
reg AESL_idle_index_reg = 0;
reg AESL_auto_restart_index_reg;
reg process_0_finish = 0;
reg process_1_finish = 0;
reg process_2_finish = 0;
reg process_3_finish = 0;
//write read_address reg
reg [31 : 0] 	write_read_address_count 			= 0;
reg 			write_read_address_run_flag 		= 0;
reg 			write_one_read_address_data_done 	= 0;

//write write_address reg
reg [31 : 0] 	write_write_address_count 			= 0;
reg 			write_write_address_run_flag 		= 0;
reg 			write_one_write_address_data_done 	= 0;
reg [31 : 0] 	write_start_count 					= 0;
reg 			write_start_run_flag 				= 0;

//write frame_size reg
reg [31 : 0] 	write_frame_size_count 			= 0;
reg 			write_frame_size_run_flag 		= 0;
reg 			write_one_frame_size_data_done 	= 0;

reg [31 : 0] 	write_width_height_count 			= 0;
reg 			write_width_height_run_flag 		= 0;
reg 			write_one_width_height_data_done 	= 0;

//===================process control=================
reg [31 : 0] ongoing_process_number = 0;
//process number depends on how much processes needed.
reg process_busy = 0;

//=================== signal connection ==============
assign TRAN_s_axi_axilite_AWADDR = AWADDR_reg;
assign TRAN_s_axi_axilite_AWVALID = AWVALID_reg;
assign TRAN_s_axi_axilite_WVALID = WVALID_reg;
assign TRAN_s_axi_axilite_WDATA = WDATA_reg;
assign TRAN_s_axi_axilite_WSTRB = WSTRB_reg;
assign TRAN_s_axi_axilite_ARADDR = ARADDR_reg;
assign TRAN_s_axi_axilite_ARVALID = ARVALID_reg;
assign TRAN_s_axi_axilite_RREADY = RREADY_reg;
assign TRAN_s_axi_axilite_BREADY = BREADY_reg;
assign TRAN_axilite_write_start_finish = AESL_write_start_finish;
assign TRAN_axilite_done_out = AESL_done_index_reg;
assign TRAN_axilite_ready_out = AESL_ready_out_index_reg;
assign TRAN_axilite_idle_out = AESL_idle_index_reg;
assign TRAN_axilite_write_data_finish = 1 & read_address_write_data_finish & write_address_write_data_finish;
always @(TRAN_axilite_ready_in or ready_initial) 
begin
    AESL_ready_reg <= TRAN_axilite_ready_in | ready_initial;
end

always @(reset or process_0_finish or process_1_finish or process_2_finish or process_3_finish ) begin
    if (reset == 0) begin
        ongoing_process_number <= 0;
    end
    else if (ongoing_process_number == 0 && process_0_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 1 && process_1_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 2 && process_2_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 3 && process_3_finish == 1) begin
            ongoing_process_number <= 0;
    end
end

always @(TRAN_read_address) 
begin
    reg_read_address = TRAN_read_address;
end
always @(TRAN_write_address) 
begin
    reg_write_address = TRAN_write_address;
end
always @(TRAN_frame_size)
begin
    reg_frame_size= TRAN_frame_size;
end

always @(TRAN_width_height)
begin
    reg_width_height = TRAN_width_height;
end


task count_c_data_four_byte_num_by_bitwidth;
input  integer bitwidth;
output integer num;
integer factor;
integer i;
begin
    factor = 32;
    for (i = 1; i <= 32; i = i + 1) begin
        if (bitwidth <= factor && bitwidth > factor - 32) begin
            num = i;
        end
        factor = factor + 32;
    end
end    
endtask

task count_seperate_factor_by_bitwidth;
input  integer bitwidth;
output integer factor;
begin
    if (bitwidth <= 8 ) begin
        factor=4;
    end
    if (bitwidth <= 16 & bitwidth > 8 ) begin
        factor=2;
    end
    if (bitwidth <= 32 & bitwidth > 16 ) begin
        factor=1;
    end
    if (bitwidth <= 1024 & bitwidth > 32 ) begin
        factor=1;
    end
end    
endtask

task count_operate_depth_by_bitwidth_and_depth;
input  integer bitwidth;
input  integer depth;
output integer operate_depth;
integer factor;
integer remain;
begin
    count_seperate_factor_by_bitwidth (bitwidth , factor);
    operate_depth = depth / factor;
    remain = depth % factor;
    if (remain > 0) begin
        operate_depth = operate_depth + 1;
    end
end    
endtask

task write; /*{{{*/
    input  reg [ADDR_WIDTH - 1:0] waddr;   // write address
    input  reg [DATA_WIDTH - 1:0] wdata;   // write data
    output reg wresp;
    reg aw_flag;
    reg w_flag;
    reg [DATA_WIDTH/8 - 1:0] wstrb_reg;
    integer i;
begin 
    wresp = 0;
    aw_flag = 0;
    w_flag = 0;
//=======================one single write operate======================
    AWADDR_reg <= waddr;
    AWVALID_reg <= 1;
    WDATA_reg <= wdata;
    WVALID_reg <= 1;
    for (i = 0; i < DATA_WIDTH/8; i = i + 1) begin
        wstrb_reg [i] = 1;
    end    
    WSTRB_reg <= wstrb_reg;
    while (!(aw_flag && w_flag)) begin
        @(posedge clk);
        if (aw_flag != 1)
            aw_flag = TRAN_s_axi_axilite_AWREADY & AWVALID_reg;
        if (w_flag != 1)
            w_flag = TRAN_s_axi_axilite_WREADY & WVALID_reg;
        AWVALID_reg <= !aw_flag;
        WVALID_reg <= !w_flag;
    end

    BREADY_reg <= 1;
    while (TRAN_s_axi_axilite_BVALID != 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    BREADY_reg <= 0;
    if (TRAN_s_axi_axilite_BRESP === 2'b00) begin
        wresp = 1;
        //input success. in fact BRESP is always 2'b00
    end   
//=======================one single write operate======================

end
endtask/*}}}*/

task read (/*{{{*/
    input  [ADDR_WIDTH - 1:0] raddr ,   // write address
    output [DATA_WIDTH - 1:0] RDATA_result ,
    output rresp
);
begin 
    rresp = 0;
//=======================one single read operate======================
    ARADDR_reg <= raddr;
    ARVALID_reg <= 1;
    while (TRAN_s_axi_axilite_ARREADY !== 1) begin
        @(posedge clk);
    end
    @(posedge clk);
    ARVALID_reg <= 0;
    RREADY_reg <= 1;
    while (TRAN_s_axi_axilite_RVALID !== 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    RDATA_result  <= TRAN_s_axi_axilite_RDATA;
    RREADY_reg <= 0;
    if (TRAN_s_axi_axilite_RRESP === 2'b00 ) begin
        rresp <= 1;
        //output success. in fact RRESP is always 2'b00
    end  
    @(posedge clk);

//=======================one single read operate end======================

end
endtask/*}}}*/

initial begin : ready_initial_process
    ready_initial = 0;
    wait(reset === 1);
    @(posedge clk);
    ready_initial = 1;
    @(posedge clk);
    ready_initial = 0;
end

initial begin : update_status
    integer process_num ;
    integer read_status_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 0;
    while (1) begin
        process_0_finish = 0;
        AESL_done_index_reg         <= 0;
        AESL_ready_out_index_reg        <= 0;
        if (ongoing_process_number === process_num && process_busy === 0) begin
            process_busy = 1;
            read (STATUS_ADDR, RDATA_reg, read_status_resp);
                AESL_done_index_reg         <= RDATA_reg[1 : 1];
                AESL_ready_out_index_reg    <= RDATA_reg[1 : 1];
                AESL_idle_index_reg         <= RDATA_reg[2 : 2];
            process_0_finish = 1;
            process_busy = 0;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        read_address_write_data_finish <= 0;
        write_read_address_run_flag <= 0; 
        write_read_address_count = 0;
        count_operate_depth_by_bitwidth_and_depth (read_address_c_bitwidth, read_address_DEPTH, read_address_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_axilite_start_in === 1) begin
            read_address_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_read_address_run_flag <= 1; 
            write_read_address_count = 0;
        end
        if (write_one_read_address_data_done === 1) begin
            write_read_address_count = write_read_address_count + 1;
            if (write_read_address_count == read_address_OPERATE_DEPTH) begin
                write_read_address_run_flag <= 0; 
                read_address_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_read_address
    integer write_read_address_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] read_address_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = read_address_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_read_address_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write read_address data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (read_address_c_bitwidth < 32) begin
                        read_address_data_tmp_reg = reg_read_address;
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < read_address_c_bitwidth) begin
                                read_address_data_tmp_reg[j] = reg_read_address[i*32 + j];
                            end
                            else begin
                                read_address_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (read_address_data_in_addr + write_read_address_count * four_byte_num * 4 + i * 4, read_address_data_tmp_reg, write_read_address_resp);
                end
                process_busy = 0;
                write_one_read_address_data_done <= 1;
                @(posedge clk);
                write_one_read_address_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_address_write_data_finish <= 0;
        write_write_address_run_flag <= 0; 
        write_write_address_count = 0;
        count_operate_depth_by_bitwidth_and_depth (write_address_c_bitwidth, write_address_DEPTH, write_address_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_axilite_start_in === 1) begin
            write_address_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_write_address_run_flag <= 1; 
            write_write_address_count = 0;
        end
        if (write_one_write_address_data_done === 1) begin
            write_write_address_count = write_write_address_count + 1;
            if (write_write_address_count == write_address_OPERATE_DEPTH) begin
                write_write_address_run_flag <= 0; 
                write_address_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_write_address
    integer write_write_address_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] write_address_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = write_address_c_bitwidth;
    process_num = 2;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_2_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_write_address_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write write_address data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (write_address_c_bitwidth < 32) begin
                        write_address_data_tmp_reg = reg_write_address;
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < write_address_c_bitwidth) begin
                                write_address_data_tmp_reg[j] = reg_write_address[i*32 + j];
                            end
                            else begin
                                write_address_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (write_address_data_in_addr + write_write_address_count * four_byte_num * 4 + i * 4, write_address_data_tmp_reg, write_write_address_resp);
                end
                process_busy = 0;
                write_one_write_address_data_done <= 1;
                @(posedge clk);
                write_one_write_address_data_done <= 0;
            end   
            process_2_finish <= 1;
        end
        @(posedge clk);
    end    
end

//=======================================================================================
//
//=======================================================================================
//{{{
always @(reset or posedge clk) begin
    if (reset == 0) begin
        width_height_write_data_finish 	<= 0;
        write_width_height_run_flag 	<= 0; 
        write_width_height_count 		= 0;
        count_operate_depth_by_bitwidth_and_depth (read_address_c_bitwidth, read_address_DEPTH, read_address_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_axilite_start_in === 1) begin
            width_height_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_width_height_run_flag <= 1; 
            write_width_height_count = 0;
        end
        if (write_one_frame_size_data_done === 1) begin
            write_width_height_count = write_width_height_count + 1;
            if (write_width_height_count == read_address_OPERATE_DEPTH) begin
                write_width_height_run_flag <= 0; 
                width_height_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_width_height
    integer write_width_height_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] width_height_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = read_address_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_width_height_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write read_address data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (read_address_c_bitwidth < 32) begin
                        width_height_data_tmp_reg = reg_width_height;
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < read_address_c_bitwidth) begin
                                width_height_data_tmp_reg[j] = reg_width_height[i*32 + j];
                            end
                            else begin
                                width_height_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (width_height_data_in_addr + write_width_height_count * four_byte_num * 4 + i * 4, width_height_data_tmp_reg, write_width_height_resp);
                end
                process_busy = 0;
                write_one_width_height_data_done <= 1;
                @(posedge clk);
                write_one_width_height_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
//}}}
//{{{
always @(reset or posedge clk) begin
    if (reset == 0) begin
        frame_size_write_data_finish 	<= 0;
        write_frame_size_run_flag 	<= 0; 
        write_frame_size_count 		= 0;
        count_operate_depth_by_bitwidth_and_depth (read_address_c_bitwidth, read_address_DEPTH, read_address_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_axilite_start_in === 1) begin
            frame_size_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_frame_size_run_flag <= 1; 
            write_frame_size_count = 0;
        end
        if (write_one_frame_size_data_done === 1) begin
            write_frame_size_count = write_frame_size_count + 1;
            if (write_frame_size_count == read_address_OPERATE_DEPTH) begin
                write_frame_size_run_flag <= 0; 
                frame_size_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_frame_size
    integer write_frame_size_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] frame_size_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = read_address_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_frame_size_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write read_address data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (read_address_c_bitwidth < 32) begin
                        frame_size_data_tmp_reg = reg_frame_size;
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < read_address_c_bitwidth) begin
                                frame_size_data_tmp_reg[j] = reg_frame_size[i*32 + j];
                            end
                            else begin
                                frame_size_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (frame_size_data_in_addr + write_frame_size_count * four_byte_num * 4 + i * 4, frame_size_data_tmp_reg, write_frame_size_resp);
                end
                process_busy = 0;
                write_one_frame_size_data_done <= 1;
                @(posedge clk);
                write_one_frame_size_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
//}}}
always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_start_run_flag <= 0; 
        write_start_count <= 0;
    end
    else begin
        if (write_start_count >= 1) begin
            write_start_run_flag <= 0; 
        end
        else if (TRAN_axilite_write_start_in === 1) begin
            write_start_run_flag <= 1; 
        end
        if (AESL_write_start_finish === 1) begin
            write_start_count <= write_start_count + 1;
            write_start_run_flag <= 0; 
        end
    end
end

initial begin : write_start
    reg [DATA_WIDTH - 1 : 0] write_start_tmp;
    integer process_num;
    integer write_start_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 3;
    while (1) begin
        process_3_finish = 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (write_start_run_flag === 1) begin
                process_busy = 1;
                write_start_tmp=0;
                write_start_tmp[0 : 0] = 1;
                write (START_ADDR, write_start_tmp, write_start_resp);
                process_busy = 0;
                AESL_write_start_finish <= 1;
                @(posedge clk);
                AESL_write_start_finish <= 0;
            end
            process_3_finish <= 1;
        end 
        @(posedge clk);
    end
end

//------------------------Task and function-------------- 
task read_token; 
    input integer fp; 
    output reg [127 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end 
endtask 
 
endmodule
