# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.srcs/sources_1/ip/layer1_line_buffer_128x256/layer1_line_buffer_128x256.xci
# IP: The module: 'layer1_line_buffer_128x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/layer1_line_buffer_128x256/layer1_line_buffer_128x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer1_line_buffer_128x256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.srcs/sources_1/ip/layer1_line_buffer_128x256/layer1_line_buffer_128x256.xci
# IP: The module: 'layer1_line_buffer_128x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/layer1_line_buffer_128x256/layer1_line_buffer_128x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer1_line_buffer_128x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
