@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Dec 27 17:44:08 +0900 2023
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim apatb_ConvNormReluPoolWrapper_top_behav -key {Behavioral:sim_1:Functional:apatb_ConvNormReluPoolWrapper_top} -tclbatch apatb_ConvNormReluPoolWrapper_top.tcl -view C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/initialization_tb_behav.wcfg -view C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/cnn_wrapper_tb.wcfg -log simulate.log"
call xsim  apatb_ConvNormReluPoolWrapper_top_behav -key {Behavioral:sim_1:Functional:apatb_ConvNormReluPoolWrapper_top} -tclbatch apatb_ConvNormReluPoolWrapper_top.tcl -view C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/initialization_tb_behav.wcfg -view C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/cnn_wrapper_tb.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
