# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0.xci
# IP: The module: 'axi_clock_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0.xci
# IP: The module: 'axi_clock_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Young Jae/OneDrive - SNU/maskgenFPGA/dfx/ip/dma/vivado/dma/dma.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
