# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/maskgenFPGA/Nexys-Video-Master.xdc

# IP: ip/l2_o_data_128x4096/l2_o_data_128x4096.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==l2_o_data_128x4096 || ORIG_REF_NAME==l2_o_data_128x4096} -quiet] -quiet
